### PR TITLE
Add minutes as a submodule

### PR DESCRIPTION
**Pull request by trickeydan**

### CODE REVIEW

**Comment by kierdavis** [comment]
Seeing as the minutes repo is known to be updated on a weekly basis, this is going to get out of date *very* easily. Surely it would be easier to just link to the minutes repo on github from a sensible place in the knowledgebase?

**Comment by kierdavis** [comment]
Also, are pull request reviews just not a thing on this repo now?

**Comment by trickeydan** [comment]
There is a bot that will update the tag, but we need a better solution. I did this at short notice as @Dasepho wanted it.

**Comment by trickeydan** [comment]
> Also, are pull request reviews just not a thing on this repo now?

I haven't been bothering with PR reviews as everybody likes ignoring that the knowledgebase exists. 

I will turn them on and require approval before merges.

**Pull request merged**
